### PR TITLE
CodeBuild requires PrivilegedMode

### PR DESCRIPTION
**Pull request by joehillen**

### CODE REVIEW

**Comment by jpignata** [comment]
Hi! This should not be necessary for the curated Docker environment. Can you tell me more about what problem you ran into that led to this pull?

**Comment by joehillen** [comment]
I built an image based on the curated one ([Dockerfile](https://github.com/awslabs/ecs-refarch-continuous-deployment/files/1732526/Dockerfile.txt)), and followed the advise given [here](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html) and it fails if not in privileged mode, [build.log](https://github.com/awslabs/ecs-refarch-continuous-deployment/files/1732521/build.log).

**Comment by joehillen** [comment]
I just tried with an [image](https://github.com/awslabs/ecs-refarch-continuous-deployment/files/1732588/Dockerfile.openjdk-8.txt) based on the newer openjdk-8 image because that now comes with Docker as of 2 days ago and without the `install` steps and it fails to log into docker, [build.log](https://github.co/awslabs/ecs-refarch-continuous-deployment/files/1732587/build-without-install-steps.log).

I'm not sure what else I should try.

**Comment by jpignata** [comment]
In these cases you're *deriving* from the curated image but not *using* the curated image, which is why privileged mode is required. This reference architecture uses the curated image directly and thus does not require the change you've proposed in this pull. Hope that makes sense.

**Comment by joehillen** [comment]
It does. Thank you.

**Pull request closed without merging**
